# Spring properties
spring:
  application:
    name: booking-service  # Service registers under this name
  messages:
    fallback-to-system-locale: false
  output:
    ansi:
      enabled: DETECT

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.gri.alex: DEBUG
    org.hibernate: ERROR

# HTTP Server
server:
  port: 2081   # HTTP (Tomcat) port

---

# For deployment in Docker containers
spring:
  profiles: docker
  # Added to fix -  java.lang.IllegalArgumentException: error at ::0 can't find referenced pointcut hystrixCommandAnnotationPointcut
  aop:
    auto: false

server:
  port: 8080
