# Spring properties
spring:
  application:
    name: booking-service  # Service registers under this name
  messages:
    fallback-to-system-locale: false

# HTTP Server
server:
  port: 2223   # HTTP (Tomcat) port
